projects/hello_django/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('pages.urls')),
    # namespace='pages' is used to avoid conflicts with other apps
    # pass a tuple of the app's urls and the app's name to include()
    # the namespace argument can then be used in the template to reference the app. it defaults to the app's name
    # if not provided
    path('', include(('pages.urls', 'pages'), namespace='pages'))
]

projects/hello_django/pages/urls.py
from django.urls import path
from .views import home_page as home_view, HomePageView, AboutPageView

urlpatterns = [
    path('func/', home_view),
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

projects/hello_django/pages/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView


def home_page(request):
    return HttpResponse("Hello, Django!")


# Use template view to render HTML
class HomePageView(TemplateView):
    template_name = 'home.html'


class AboutPageView(TemplateView):
    template_name = 'about.html'

projects/hello_django/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
{% endblock %}

projects/hello_django/templates/base.html
<header>
  <a href="{% url 'pages:home' %}" class="">Home</a>
  <a href="{% url 'pages:about' %}" class="">About</a>
</header>
{% block content %} {% endblock %}

projects/hello_django/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Homepage</h1>
{% endblock %}