projects/blog/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

projects/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include('accounts.urls')),
    path('', include('blogs.urls')),
]

projects/blog/blogs/urls.py
from django.urls import path

from .views import BlogsHomeViews, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

urlpatterns = [
    path('', BlogsHomeViews.as_view(), name='home'),
    # specify the primary key of the blog object in the URL
    # parameters are passed to the views as arguments
    # the type must be specified in the format <type:param>
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/new/', BlogCreateView.as_view(), name='new_blog'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

projects/blog/blogs/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # use the reverse() function to return a URL string of a view
        return reverse('blog_detail', kwargs={'pk': self.pk})

projects/blog/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy


class SignUpView(CreateView):
    # specify form class to use a custom form
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

projects/blog/blogs/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Blog


class BlogsHomeViews(ListView):
    # Default context_object_name is <model_name_list> in lowercase
    model = Blog
    template_name = 'home.html'


class BlogDetailView(DetailView):
    # Default context_object_name is model name in lowercase or object
    model = Blog
    # blog_detail.html is in the blogs app directory
    template_name = 'blogs/blog_detail.html'


class BlogCreateView(CreateView):
    model = Blog
    # use '__all__' to include all fields in the form
    fields = ['title', 'author', 'body', ]
    template_name = 'blogs/new_blog.html'


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'body']
    template_name = 'blogs/blog_update.html'


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blogs/blog_delete.html'
    success_url = reverse_lazy('home')
    # success_url = '/' # this is also valid but reverse_lazy is preferred as this is hard-coded

projects/blog/blogs/templates/blogs/blog_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete blog</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ blog.title }}"?</p>
      <input type="submit" value="Confirm">
    </form>
{% endblock content %}

projects/blog/blogs/templates/blogs/blog_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="blog-entry">
    <h2>{{ blog.title }}</h2>
    <p>{{ blog.body }}</p>
  </div>
  <p><a href="{% url 'blog_update' blog.pk %}">+ Edit Blog Post</a></p>
  <p><a href="{% url 'blog_delete' blog.pk %}">- Delete Blog Post</a></p>
{% endblock content %}

projects/blog/blogs/templates/blogs/blog_update.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" action="">
    <!-- always add for post methods -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock content %}

projects/blog/blogs/templates/blogs/new_blog.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" action="">
    <!-- always add for post methods -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock content %}

projects/blog/templates/base.html
{% load static %}
<html>
  <head>
    <title>Django blog</title>
    <link href="https://fonts.googleapis.com/css?family=\Source+Sans+Pro:400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <header>
      <h1><a href="{% url 'home' %}">Django blog</a></h1>
      <div class="nav-right">
        <a href="{% url 'new_blog' %}">+ New Blog Post</a>
      </div>
    </header>
    <div>
      {% if user.is_authenticated %}
        <p>Hi {{user.username}}!</p>
        <p><a href="{% url 'logout' %}">Log Out</a></p>
      {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
        <a href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

projects/blog/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% for blog in blog_list %}
      <div class="blog-entry">
        <h2><a href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></h2>
        <p>{{ blog.body }}</p>
      </div>
    {% endfor %}

{% endblock content %}